import type { GuideGroup } from '../types';

// Nguồn: ThongKePagePlan.tsx, LenhSanXuatPhoi.tsx, XacNhanNhanSatPage.tsx, KhoPhoiPage.tsx,
// HuongDanCatPage.tsx, VatTuTpDetail.tsx, LenhSanXuatHan.tsx, LenhSanXuatSon.tsx,
// XacNhanVatTuPage.tsx, KcsPhoiPage.tsx, KcsHanPage.tsx/KcsSonPage.tsx (kcsCore.tsx),
// SpecSteelPage.tsx, SpecDetailQuotaPage.tsx, SpecAccessoryCatalogPage.tsx +
// BE production-orders/floor-gate/steel-issues/qc-reviews/production-batches —
// đọc trực tiếp mã nguồn 22/09/2026.

export const manufacturingGroup: GuideGroup = {
  id: 'manufacturing',
  title: 'Sản xuất (Phôi · Hàn · Sơn · KCS)',
  icon: 'Factory',
  color: '#C2410C',
  bg: '#FFEDD5',
  roles: ['qlsx', 'phoi', 'han', 'son', 'kcs', 'spec_steel', 'spec_detail'],
  description: 'Điều hành xưởng: bấm Bắt đầu/Kết thúc lệnh, cắt sắt, hàn, sơn, kiểm tra chất lượng, nhập định mức.',
  articles: [
    {
      id: 'mfg-floor-gate',
      title: 'Nguyên tắc chung: gate "Bắt đầu" / "Kết thúc" của QLSX',
      roles: ['qlsx', 'phoi', 'han', 'son', 'kcs'],
      purpose:
        'QLSX là người bật/tắt quyền được thao tác trên xưởng cho một lệnh sản xuất (PI). Mọi hành động ghi nhận dưới xưởng — xuất vật tư, báo sản lượng, KCS duyệt, chuyền kiểm, đóng gói — đều bị khoá cho tới khi QLSX bấm "Bắt đầu".',
      mock: { title: 'Tổng hợp lệnh SX', buttons: ['Tạm dừng', 'Bắt đầu', 'Kết thúc'] },
      screenshot: '/guide-screens/mfg-floor-gate.png',
      steps: [
        'QLSX mở "Tổng hợp lệnh SX", tìm PI cần xử lý.',
        { text: 'Bấm "Bắt đầu" — xác nhận trong hộp thoại. Trạng thái chuyển sang "Đang chạy", mọi thao tác dưới xưởng cho PI này được mở khoá.', critical: true },
        'Trong lúc đang chạy, có thể bấm "Tạm dừng" (khoá lại tạm thời) rồi "Tiếp tục" khi cần.',
        { text: 'Khi xong toàn bộ, bấm "Kết thúc" — xác nhận "Không thể hoàn tác thao tác này".', critical: true },
      ],
      result: 'PI ở đúng trạng thái phản ánh việc xưởng có đang được phép làm việc hay không.',
      warnings: [
        'Quy tắc mở khoá tính theo CẢ PI: chỉ cần ít nhất 1 SKU bất kỳ trong PI đang "Đang chạy" là mọi thao tác thuộc PI đó đều được phép — không cần đúng SKU đang thao tác phải ở trạng thái đó riêng.',
        '"Kết thúc" không thể hoàn tác. "Tạm dừng" sẽ khoá lại TOÀN BỘ PI (không riêng SKU đang tạm dừng) nếu đó là SKU cuối cùng đang chạy.',
        'Nếu PI có định mức mới hơn bản đang áp dụng, nút "Nạp lại định mức" chỉ dùng được khi PI còn ở trạng thái "Chưa bắt đầu" (chưa bấm Bắt đầu lần nào) và chưa có phương án cắt nào đã duyệt.',
      ],
      commonErrors: [
        { issue: 'Bất kỳ thao tác nào dưới xưởng báo lỗi dạng "PI ... chưa có SKU nào được QLSX bấm \'Bắt đầu\' (hoặc đã \'Kết thúc\') - chưa/không thể ..."', cause: 'QLSX chưa bấm "Bắt đầu" cho PI này, hoặc đã bấm "Kết thúc" rồi.', fix: 'Liên hệ QLSX kiểm tra và bấm "Bắt đầu" (hoặc "Tiếp tục" nếu đang Tạm dừng) trước khi thao tác.' },
      ],
      statuses: [
        { name: 'Chưa bắt đầu', meaning: 'Mọi thao tác dưới xưởng cho PI này bị khoá.' },
        { name: 'Đang chạy', meaning: 'Xưởng được phép thao tác.' },
        { name: 'Tạm dừng', meaning: 'Khoá lại tạm thời.' },
        { name: 'Đã kết thúc', meaning: 'Trạng thái cuối, không thể quay lại.' },
      ],
      tags: ['bắt đầu', 'kết thúc', 'floor stage', 'gate qlsx', 'tạm dừng'],
      sourceRefs: ['src/modules/pages/Manufacturing/ThongKePagePlan.tsx', 'DNA-ERP-BE/src/common/utils/floor-gate.util.ts'],
    },
    {
      id: 'mfg-phoi-cat',
      title: 'Tổ Phôi — cắt sắt',
      roles: ['phoi'],
      purpose: 'Cắt sắt theo phương án đã được duyệt, báo số lượng đã cắt xong theo từng SKU.',
      preconditions: [
        'PI đã được QLSX bấm "Bắt đầu".',
        'Đã nhận cây sắt từ Thủ kho (xem bài "Xác nhận nhận sắt").',
      ],
      mock: {
        title: 'Lệnh sản xuất — Phôi',
        columns: ['Cỡ đoạn', 'Cần', 'Đã cắt', 'Nhập đợt này'],
        rows: [['400mm', '200', '120', '___'], ['700mm', '150', '90', '___']],
        buttons: ['Lưu đợt cắt', 'Gửi KCS'],
      },
      screenshot: '/guide-screens/mfg-phoi-cat.png',
      steps: [
        'Ở "Lệnh sản xuất", chọn SKU đang cắt (bắt buộc chọn đúng SKU — hệ thống chỉ cho khai cỡ đoạn có trong định mức của chính SKU đó).',
        'Nhập số đoạn đã cắt được cho từng cỡ vào ô "Nhập đợt này", bấm "Lưu đợt cắt" — có thể lưu nhiều đợt, cộng dồn dần.',
        { text: 'Khi đã cắt xong đủ (hoặc muốn báo một phần), bấm "Gửi KCS".', critical: true },
        'Nếu lỡ nhập sai, dùng "Hoàn tác" — CHỈ hoàn tác được lần lưu gần nhất.',
      ],
      result: 'Đợt cắt chuyển sang chờ KCS kiểm tra; sau khi KCS duyệt, phần đạt chuyển tiếp cho Tổ Hàn.',
      warnings: [
        'Hệ thống KHÔNG chặn nhập vượt số "Còn lại" theo định mức — số liệu chỉ mang tính tham khảo, việc kiểm soát dồn hết về bước KCS duyệt.',
        '"Hoàn tác" chỉ nhớ đúng 1 bước gần nhất — lưu thêm một đợt khác hoặc rời trang là mất khả năng hoàn tác đợt trước đó.',
        'Nếu KCS "trả về", đợt đó không tự sinh lô làm lại — bạn sẽ thấy badge "KCS trả về · cắt lại" và tự cắt bù một đợt mới, dùng nút "Bù đủ" để tự điền sẵn số lượng cần bù.',
      ],
      commonErrors: [
        { issue: '"Steel issue ... chưa được xác nhận nhận - xác nhận ở \'Xác nhận nhận sắt\' trước khi nhập đợt cắt"', cause: 'Chưa xác nhận đã nhận cây sắt từ Thủ kho.', fix: 'Vào "Xác nhận nhận sắt", bấm xác nhận trước.' },
        { issue: '"SKU (lệnh sản xuất ...) không thuộc PI của lô sắt này"', cause: 'Chọn nhầm SKU không thuộc đúng PI của lô sắt đang cắt.', fix: 'Chọn lại đúng SKU thuộc PI này.' },
        { issue: '"Cỡ đoạn ... không có trong định mức của SKU đã chọn"', cause: 'Khai một cỡ đoạn không có trong công thức sản xuất (định mức) của SKU.', fix: 'Kiểm tra lại định mức đúng của SKU trước khi khai, hoặc chọn đúng mảnh/cỡ đoạn.' },
      ],
      statuses: [
        { name: 'Đang mở', meaning: 'Có thể tiếp tục lưu thêm đợt cắt.' },
        { name: 'Chờ KCS duyệt', meaning: 'Đã gửi, chờ KCS kiểm tra.' },
        { name: 'KCS đã duyệt', meaning: 'Đã có kết quả kiểm tra chất lượng.' },
      ],
      tags: ['cắt sắt', 'phôi', 'lưu đợt cắt', 'gửi kcs'],
      sourceRefs: ['src/modules/pages/Phoi/LenhSanXuatPhoi.tsx'],
    },
    {
      id: 'mfg-phoi-nhan-sat',
      title: 'Tổ Phôi — xác nhận nhận sắt / vật tư TP',
      roles: ['phoi'],
      purpose: 'Xác nhận đã nhận đợt sắt (hoặc vật tư thành phẩm) mà Thủ kho vừa xuất, trước khi cắt.',
      mock: {
        title: 'Xác nhận nhận sắt',
        columns: ['Vật tư', 'Số lượng đã xuất', 'Trạng thái'],
        rows: [['Sắt hộp 20x20 · dài 6000mm', '200 cây', 'Đã xuất']],
        buttons: ['Xác nhận đã nhận'],
      },
      screenshot: '/guide-screens/mfg-phoi-nhan-sat.png',
      steps: [
        { text: 'Ở tab "Xác nhận", bấm "Xác nhận đã nhận" cho từng đợt Thủ kho đã xuất.', critical: true },
        'Xem lại lịch sử đã xác nhận ở tab "Lịch sử".',
      ],
      result: 'Đợt xuất chuyển từ "Đã xuất" sang "Đã nhận" — chỉ sau bước này mới nhập đợt cắt được cho lô sắt tương ứng.',
      commonErrors: [
        { issue: '"Không xác nhận được"', cause: 'PI chưa được QLSX bấm "Bắt đầu", hoặc lỗi khác từ máy chủ.', fix: 'Kiểm tra trạng thái PI với QLSX rồi thử lại.' },
      ],
      tags: ['xác nhận nhận sắt', 'nhận vật tư thành phẩm'],
      sourceRefs: ['src/modules/pages/Phoi/XacNhanNhanSatPage.tsx'],
    },
    {
      id: 'mfg-phoi-vattutp',
      title: 'Tổ Phôi — Vật tư thành phẩm (chân nhôm, sắt la...)',
      roles: ['phoi'],
      purpose: 'Báo sản lượng gia công cho các mảnh "vật tư thành phẩm" (loại mảnh cắt theo tỷ lệ cố định, không cần qua Hàn).',
      mock: {
        title: 'Vật tư TP — Pat/Chân nhôm',
        columns: ['Mảnh', 'Cần', 'Đã báo'],
        rows: [['Chân nhôm', '279', '180']],
        buttons: ['Lưu đợt', 'Gửi KCS'],
      },
      screenshot: '/guide-screens/mfg-phoi-vattutp.png',
      steps: [
        'Với mảnh không có nhiều bước gia công: nhập số lượng, bấm "Lưu đợt" rồi "Gửi KCS".',
        'Với mảnh có khai nhiều bước (VD: cắt → dập): báo từng bước riêng, mỗi bước tự "Lưu đợt"/"Gửi KCS".',
      ],
      result: 'Ở bước cuối cùng, khi hoàn tất, hệ thống tự động chốt và gửi KCS — không cần thao tác "Chốt & gửi KCS" thủ công riêng nữa.',
      tags: ['vật tư thành phẩm', 'chân nhôm', 'pat'],
      sourceRefs: ['src/modules/pages/Phoi/VatTuTpDetail.tsx'],
    },
    {
      id: 'mfg-phoi-tra-cuu',
      title: 'Tổ Phôi — tra cứu (Kho phôi, Hướng dẫn cắt, Định mức mảnh)',
      roles: ['phoi'],
      purpose: 'Các màn chỉ xem, hỗ trợ Tổ Phôi làm việc chính xác hơn.',
      screenshot: '/guide-screens/mfg-phoi-tra-cuu.png',
      steps: [
        '"Kho phôi": xem tồn đoạn sắt thật tại kho (Đoạn chuẩn chờ chuyển Hàn / Đoạn thừa chờ xử lý).',
        '"Hướng dẫn cắt": xem bảng cắt bắt buộc theo phương án đã duyệt cho PO/PI, có thể bấm "In" (Excel/PDF).',
        '"Danh sách định mức mảnh": tra nhanh định mức sắt của từng mảnh theo SKU.',
      ],
      result: 'Có đủ thông tin tham khảo khi cắt, không cần hỏi lại KHSX.',
      warnings: ['"Hướng dẫn cắt" hiện thông báo "Chưa có phương án cắt nào đã duyệt cho PO/PI này" nếu KHSX chưa duyệt xong phương án.'],
      tags: ['kho phôi', 'hướng dẫn cắt', 'định mức mảnh'],
      sourceRefs: ['src/modules/pages/Phoi/KhoPhoiPage.tsx', 'src/modules/pages/Phoi/HuongDanCatPage.tsx'],
    },
    {
      id: 'mfg-han-son',
      title: 'Tổ Hàn / Tổ Sơn — báo sản lượng',
      roles: ['han', 'son'],
      purpose: 'Báo số lượng đã hàn (hoặc đã sơn) xong theo từng mảnh của SKU.',
      preconditions: ['PI đã được QLSX bấm "Bắt đầu".'],
      mock: {
        title: 'Lệnh sản xuất — Hàn/Sơn',
        columns: ['Mảnh', 'Cần', 'Đã báo', 'Còn lại'],
        rows: [['Mảnh tựa', '200', '150', '50']],
        buttons: ['Lưu đợt', 'Gửi KCS'],
      },
      screenshot: '/guide-screens/mfg-han-son.png',
      steps: [
        'Mở "Lệnh sản xuất", chọn PI → SKU → mảnh cần báo.',
        'Nhập số lượng vào ô, bấm "Lưu đợt" — cộng dồn vào đợt đang mở.',
        { text: 'Bấm "Gửi KCS" khi muốn chuyển đợt đang mở sang chờ kiểm tra.', critical: true },
      ],
      result: 'Đợt chuyển sang chờ KCS duyệt; sau khi KCS duyệt xong, sản phẩm sẵn sàng cho công đoạn tiếp theo (Sơn, hoặc Đan/Chuyền kiểm nếu là Sơn).',
      warnings: [
        'Không chặn nhập vượt số "Còn lại" theo định mức — số liệu chỉ mang tính tham khảo.',
        'Nếu KCS chấm có lỗi, KCS KHÔNG tự tạo lô làm lại cho Hàn/Sơn — phải tự báo một đợt hoàn toàn mới (dùng "Bù đủ" để tự điền số cần bù) và gửi KCS lại như bình thường.',
        'Banner đỏ "chưa cân đối" xuất hiện khi các mảnh của cùng một SKU chưa cắt/hàn/sơn đều số lượng với nhau — cần chú ý để tránh lệch dây chuyền.',
      ],
      commonErrors: [
        { issue: '"Batch ... đang ở trạng thái ... - chỉ đợt đang mở mới gửi KCS được"', cause: 'Đợt đã được gửi KCS rồi, không gửi lại được nữa.', fix: 'Mở một đợt mới nếu cần báo thêm.' },
        { issue: '"Chưa có gì để gửi KCS"', cause: 'Bấm "Gửi KCS" khi chưa nhập số lượng nào.', fix: 'Nhập số lượng trước khi gửi.' },
      ],
      statuses: [
        { name: 'Đang mở', meaning: 'Đợt còn có thể tiếp tục lưu thêm sản lượng.' },
        { name: 'Chờ KCS duyệt', meaning: 'Đã gửi, chờ KCS kiểm tra.' },
        { name: 'KCS đã duyệt', meaning: 'Đã có kết quả kiểm tra chất lượng.' },
      ],
      tags: ['hàn', 'sơn', 'báo sản lượng', 'lưu đợt', 'gửi kcs'],
      sourceRefs: ['src/modules/pages/Han/LenhSanXuatHan.tsx', 'src/modules/pages/Son/LenhSanXuatSon.tsx'],
    },
    {
      id: 'mfg-han-son-nhan-vattu',
      title: 'Tổ Hàn / Tổ Sơn — xác nhận nhận vật tư tiêu hao',
      roles: ['han', 'son'],
      purpose: 'Xác nhận đã nhận vật tư tiêu hao (khí CO2, dây hàn, bột sơn...) do Thủ kho cấp — khác hẳn Sắt, không qua KCS.',
      mock: {
        title: 'Xác nhận nhận vật tư',
        columns: ['Vật tư', 'Đã xuất', 'Trạng thái'],
        rows: [['Khí CO2', '25', 'Đã xuất']],
        buttons: ['Nhận thiếu', 'Xác nhận đã nhận'],
      },
      screenshot: '/guide-screens/mfg-han-son-nhan-vattu.png',
      steps: [
        { text: 'Bấm "Xác nhận đã nhận" nếu nhận đủ.', critical: false },
        { text: 'Hoặc bấm "Nhận thiếu" để sửa số thực nhận, rồi "Lưu & xác nhận".', critical: false },
      ],
      result: 'Đợt xuất vật tư chuyển từ "Đã xuất" sang "Đã nhận".',
      commonErrors: [
        { issue: '"Không thể xác nhận nhận vật tư"', cause: 'Lỗi chung từ máy chủ (PI chưa Bắt đầu, hoặc lỗi khác).', fix: 'Kiểm tra trạng thái PI với QLSX rồi thử lại.' },
      ],
      tags: ['nhận vật tư tiêu hao', 'khí co2', 'dây hàn', 'bột sơn'],
      sourceRefs: ['src/modules/pages/Manufacturing/XacNhanVatTuPage.tsx'],
    },
    {
      id: 'mfg-kcs-han-son',
      title: 'KCS — duyệt Hàn / Sơn / Vật tư TP',
      roles: ['kcs'],
      purpose: 'Kiểm tra chất lượng các đợt Hàn/Sơn/Vật tư TP đang chờ, chấm đạt/không đạt.',
      preconditions: ['Có đợt đang ở trạng thái chờ KCS kiểm tra.'],
      mock: {
        title: 'KCS — duyệt Hàn/Sơn',
        formFields: ['Số lượng chưa đạt', 'Nguyên nhân không đạt *', 'Ghi chú', 'Hình ảnh'],
        buttons: ['+ Thêm loại lỗi mới…', 'Xác nhận duyệt'],
      },
      screenshot: '/guide-screens/mfg-kcs-han-son.png',
      steps: [
        'Chọn dòng có số lượng chờ duyệt, bấm "Tiến hành duyệt".',
        'Nhập "Số lượng chưa đạt" (0 nếu đạt hết).',
        { text: 'Nếu có số chưa đạt: bắt buộc chọn "Nguyên nhân không đạt" (có thể thêm loại lỗi mới nếu chưa có sẵn), có thể ghi chú và đính kèm ảnh.', critical: false },
        { text: 'Bấm "Xác nhận duyệt".', critical: true },
      ],
      result: 'Đợt chuyển sang đã duyệt (kể cả khi còn phần không đạt) — hệ thống chỉ có 2 kết quả Đạt/Không đạt, không còn phân loại "sửa được/phế".',
      warnings: [
        'QUAN TRỌNG: KCS KHÔNG tự tạo lô làm lại cho phần không đạt, ở bất kỳ công đoạn nào (Phôi/Hàn/Sơn/Vật tư TP). Số "Không đạt" chỉ là ghi nhận lịch sử (cộng dồn, không tự giảm) — tổ sản xuất phải tự báo một đợt/lô hoàn toàn mới để bù, dùng nút "Bù đủ" bên màn báo sản lượng để tự điền sẵn số cần bù.',
        'Modal duyệt giữ nguyên dữ liệu đã nhập nếu xác nhận thất bại — không cần nhập lại từ đầu.',
      ],
      commonErrors: [
        { issue: '"Production batch ... đang ở trạng thái ... - chỉ đợt đang chờ KCS mới duyệt được"', cause: 'Đợt đã được duyệt trước đó rồi (bấm 2 lần hoặc 2 người cùng duyệt).', fix: 'Tải lại danh sách để xem trạng thái mới nhất.' },
        { issue: '"failedQty (...) không được vượt số lượng đã báo (...)"', cause: 'Nhập số không đạt lớn hơn tổng số đã báo của đợt đó.', fix: 'Kiểm tra lại số lượng đã báo trước khi nhập số không đạt.' },
      ],
      tags: ['kcs', 'duyệt kcs', 'chất lượng', 'qc review'],
      sourceRefs: ['src/modules/pages/Kcs/KcsHanPage.tsx', 'src/modules/pages/Kcs/KcsSonPage.tsx'],
    },
    {
      id: 'mfg-kcs-phoi',
      title: 'KCS — duyệt Phôi (cắt sắt)',
      roles: ['kcs'],
      purpose: 'Kiểm tra chất lượng đợt cắt sắt, chấm đạt/không đạt theo TỪNG CỠ ĐOẠN (khác Hàn/Sơn chấm theo tổng số lượng).',
      mock: {
        title: 'KCS — duyệt Phôi',
        columns: ['Cỡ đoạn', 'Đã cắt', 'Không đạt'],
        rows: [['400mm', '120', '___'], ['700mm', '90', '___']],
        buttons: ['Xác nhận duyệt'],
      },
      screenshot: '/guide-screens/mfg-kcs-phoi.png',
      steps: [
        'Chọn tab công đoạn (Cắt, Uốn, Dập...) — mỗi tab có badge số đang chờ duyệt.',
        'Mở đợt cần duyệt: với mỗi cỡ đoạn, nhập số "Không đạt" riêng.',
        { text: 'Nếu có lỗi: chọn nguyên nhân (bắt buộc), bấm "Xác nhận duyệt".', critical: true },
      ],
      result: 'Đợt cắt đóng lại (coi như đã kiểm xong) ngay cả khi còn lỗi — giống nguyên tắc chung của KCS, không tự sinh đợt cắt lại; Tổ Phôi tự cắt bù bằng một đợt mới.',
      warnings: ['Chấm lỗi theo đúng đợt cắt hiện tại — không được chấm số lỗi vượt quá số đã cắt của CHÍNH đợt đang duyệt (không cộng dồn với các đợt khác trong cùng PI).'],
      commonErrors: [
        { issue: '"Chấm lỗi ... đoạn ...mm vượt số đã cắt (...) trong chính đợt cắt này"', cause: 'Nhập số không đạt lớn hơn số đã cắt của đúng cỡ đoạn trong đợt này.', fix: 'Kiểm tra lại số đã cắt của đúng đợt trước khi chấm.' },
        { issue: '"Đợt cắt ... đã bị 1 request khác duyệt KCS trong lúc đang xử lý"', cause: '2 người cùng duyệt một đợt gần như đồng thời.', fix: 'Tải lại trang, kiểm tra trạng thái mới nhất.' },
      ],
      tags: ['kcs phôi', 'duyệt cắt sắt', 'chấm theo cỡ đoạn'],
      sourceRefs: ['src/modules/pages/Kcs/KcsPhoiPage.tsx'],
    },
    {
      id: 'mfg-spec-steel',
      title: 'Chuyên viên định mức mảnh — nhập định mức Sắt/Dây/Đinh',
      roles: ['spec_steel'],
      purpose: 'Nhập định mức vật tư cho từng mảnh của một SKU: sắt cần cắt, dây, đinh, tán rút, nút nhựa.',
      preconditions: ['SKU đã được KHSX tạo (ở màn "Duyệt SKU").'],
      mock: {
        title: 'Định mức mảnh',
        columns: ['Mảnh', 'Chiều dài sắt', 'Số đoạn', 'Dây', 'Đinh'],
        rows: [['Mảnh tựa', '400mm', '2', '2m', '8']],
        buttons: ['Gửi phê duyệt'],
      },
      screenshot: '/guide-screens/mfg-spec-steel.png',
      steps: [
        'Mở SKU, bấm thêm mảnh mới nếu cần.',
        'Với mỗi mảnh: khai chiều dài sắt cần cắt + số đoạn, và các vật tư phụ (dây/đinh/tán rút/nút nhựa) — chọn vật tư từ danh mục có sẵn (do Admin khai báo trước, không gõ tự do).',
        { text: 'Bấm "Gửi phê duyệt" khi đã nhập xong.', critical: true },
      ],
      result: 'Dữ liệu định mức mảnh chuyển sang chờ KHSX duyệt.',
      warnings: [
        'Mỗi lần bấm "Gửi phê duyệt" là GHI ĐÈ TOÀN BỘ danh sách mảnh của SKU đó — không phải sửa từng dòng.',
        'Ảnh minh hoạ (nếu có) chỉ thực sự tải lên khi bấm "Gửi phê duyệt" — chọn ảnh trước đó chỉ là xem trước.',
      ],
      commonErrors: [
        { issue: '"Không thể gửi phê duyệt"', cause: 'Lỗi chung khi gửi thất bại.', fix: 'Kiểm tra lại dữ liệu đã nhập và thử lại.' },
      ],
      statuses: [
        { name: 'Có thể nhập', meaning: 'Chưa từng gửi, hoặc KHSX vừa từ chối — có thể nhập/sửa.' },
        { name: 'Đang chờ', meaning: 'Đã gửi, chờ KHSX duyệt.' },
        { name: 'Đã duyệt / Từ chối', meaning: 'KHSX đã xử lý xong.' },
      ],
      tags: ['định mức mảnh', 'spec steel', 'nhập bom sắt'],
      sourceRefs: ['src/modules/pages/Manufacturing/SpecSteelPage.tsx'],
    },
    {
      id: 'mfg-spec-detail',
      title: 'Chuyên viên định mức chi tiết — nhập định mức Sơn/Phụ kiện/Bao bì',
      roles: ['spec_detail'],
      purpose: 'Nhập định mức sơn, phụ kiện và bao bì đóng gói cho cả sản phẩm (không theo từng mảnh).',
      preconditions: ['SKU đã được KHSX tạo — có thể bắt đầu ngay, không cần chờ chuyên viên định mức mảnh.'],
      mock: {
        title: 'Định mức chi tiết',
        columns: ['Nhóm', 'Vật tư', 'Số lượng/sản phẩm'],
        rows: [['Sơn', 'Sơn xám RAL7035', '0.2 lít'], ['Bao bì', 'Thùng carton 60x40', '1']],
        buttons: ['Gửi phê duyệt'],
      },
      screenshot: '/guide-screens/mfg-spec-detail.png',
      steps: [
        'Mở SKU, thêm dòng định mức cho từng nhóm: Sơn / Phụ kiện / Bao bì — chọn vật tư từ danh mục có sẵn.',
        { text: 'Bấm "Gửi phê duyệt".', critical: true },
      ],
      result: 'Dữ liệu định mức chi tiết chuyển sang chờ KHSX duyệt, độc lập với nhánh định mức mảnh.',
      warnings: [
        'Một vật tư chỉ thuộc đúng một trong ba nhóm (Sơn/Phụ kiện/Bao bì) ngay từ khi Admin khai báo — muốn đổi nhóm phải sửa ở danh mục gốc (Admin), không sửa được từ màn này.',
        'Mỗi lần "Gửi phê duyệt" là ghi đè toàn bộ danh sách dòng chi tiết của SKU đó.',
      ],
      tags: ['định mức chi tiết', 'spec accessory', 'sơn', 'phụ kiện', 'bao bì'],
      sourceRefs: ['src/modules/pages/Manufacturing/SpecDetailQuotaPage.tsx', 'src/modules/pages/Manufacturing/SpecAccessoryCatalogPage.tsx'],
    },
  ],
};
