import type { GuideGroup } from '../types';

// Nguồn: ProductionPlanApp.tsx, SKUListPage.tsx, SKUReviewPage.tsx, SKUDetail.tsx, LenhSXPage.tsx,
// GomDotCatPage.tsx, VatTuDashboardPage.tsx, BE skus.service.ts — đọc trực tiếp mã nguồn 22/09/2026.

export const productionPlanGroup: GuideGroup = {
  id: 'production-plan',
  title: 'Kế hoạch sản xuất',
  icon: 'LayoutDashboard',
  color: 'var(--fg-0e7490)',
  bg: 'var(--bg-cffafe)',
  roles: ['khsx', 'qlsx', 'boss'],
  description: 'Tạo sản phẩm mới, duyệt định mức, gộp đợt cắt sắt, lập và trình duyệt lệnh sản xuất.',
  articles: [
    {
      id: 'pp-danh-sach-sku',
      title: 'Danh sách SKU',
      roles: ['khsx'],
      purpose: 'Xem lại toàn bộ SKU đã tạo, lọc theo trạng thái, xoá SKU không cần dùng nữa.',
      screenshot: '/guide-screens/pp-danh-sach-sku.png',
      mock: {
        title: 'Danh sách SKU',
        columns: ['SKU', 'Sản phẩm', 'Khách hàng', 'Trạng thái'],
        rows: [['GHE-001', 'Ghế ăn mây nhựa', 'Công ty ABC', 'Đã duyệt'], ['BAN-014', 'Bàn cà phê tròn', 'Công ty XYZ', 'Đang làm định mức']],
        buttons: ['Xóa SKU'],
      },
      steps: [
        'Lọc theo trạng thái bằng các pill: Tất cả / Đang làm định mức / Chờ sếp duyệt / Đã duyệt.',
        'Tìm theo mã SKU, tên sản phẩm hoặc Mã khách hàng.',
        'Click một dòng để xem chi tiết (chỉ xem, không duyệt được từ đây).',
        { text: 'Xoá: bấm "Xóa SKU" để vào chế độ chọn → tick các dòng cần xoá → "Xóa N mục" → xác nhận trong hộp thoại.', critical: true },
      ],
      result: 'Danh sách SKU được cập nhật; các SKU đã xoá biến mất khỏi mọi nơi trong hệ thống.',
      warnings: [
        'Xoá SKU là XOÁ CỨNG, không thể hoàn tác — kể cả SKU đã ở trạng thái Đã duyệt. Toàn bộ dữ liệu định mức mảnh/chi tiết liên quan cũng bị xoá theo.',
      ],
      commonErrors: [
        { issue: '"Không thể xóa"', cause: 'Lỗi chung khi thao tác xoá thất bại (nhiều nguyên nhân khác nhau, hệ thống không phân biệt rõ).', fix: 'Thử lại; nếu vẫn lỗi, liên hệ Admin kiểm tra.' },
      ],
      tags: ['danh sách sku', 'xoá sku'],
      sourceRefs: ['src/modules/pages/ProductionPlan/SKUListPage.tsx'],
    },
    {
      id: 'pp-tao-sku',
      title: 'Tạo SKU mới',
      roles: ['khsx'],
      purpose: 'Khởi tạo hồ sơ cho một sản phẩm mới, làm điểm bắt đầu để hai chuyên viên định mức nhập dữ liệu.',
      screenshot: '/guide-screens/pp-tao-sku.png',
      mock: {
        title: 'Tạo SKU mới',
        formFields: ['SKU *', 'Mã khách hàng'],
        buttons: ['Thêm SKU'],
      },
      steps: [
        'Ở màn "Duyệt SKU", bấm "Tạo SKU mới".',
        'Nhập SKU (mã sản phẩm, bắt buộc) và Mã khách hàng (tuỳ chọn, gõ tự do hoặc chọn có sẵn).',
        'Bấm "Thêm SKU".',
      ],
      result: 'Hồ sơ SKU rỗng được tạo, trạng thái "Đang làm định mức" — sẵn sàng cho hai chuyên viên định mức bắt đầu nhập liệu.',
      warnings: [
        'Nếu mã SKU trùng với một sản phẩm đã có hồ sơ định mức chưa duyệt xong, hệ thống chỉ cảnh báo mềm ("Sản phẩm đã có hồ sơ định mức") kèm nút "Vẫn tạo mới" — không chặn cứng.',
      ],
      commonErrors: [
        { issue: '"Vui lòng nhập SKU"', cause: 'Chưa nhập mã SKU.', fix: 'Nhập mã SKU rồi thử lại.' },
        { issue: '"Product ... already exists"', cause: 'Mã SKU đã tồn tại là mã sản phẩm chính thức.', fix: 'Đổi sang mã khác hoặc dùng đúng hồ sơ đã có.' },
      ],
      tags: ['tạo sku', 'sản phẩm mới'],
      sourceRefs: ['src/modules/pages/ProductionPlan/SKUReviewPage.tsx'],
    },
    {
      id: 'pp-duyet-sku',
      title: 'Duyệt định mức SKU (KHSX)',
      roles: ['khsx'],
      purpose: 'Xem xét và duyệt dữ liệu định mức do hai chuyên viên nhập, chốt từng nhánh trước khi hồ sơ tự chuyển cho Giám đốc.',
      preconditions: ['Chuyên viên định mức mảnh và/hoặc chi tiết đã nhập dữ liệu cho SKU.'],
      screenshot: '/guide-screens/pp-duyet-sku.png',
      mock: {
        title: 'Duyệt SKU — Định mức mảnh',
        columns: ['Mảnh', 'Sắt', 'Dây', 'Đinh', 'Tán rút', 'Nút nhựa'],
        rows: [['Mảnh tựa', 'Ø14 x 400mm', '2m', '8', '4', '4'], ['Mảnh chân', 'Ø16 x 700mm', '—', '6', '—', '4']],
        buttons: ['Từ chối', 'Duyệt', 'Xác nhận hoàn tất'],
      },
      steps: [
        'Lọc nhanh theo: Chờ duyệt mảnh / Chờ duyệt chi tiết / Chờ sếp duyệt.',
        'Mở chi tiết SKU, xem tab "Định mức mảnh": bảng theo từng mảnh, gồm 6 nhóm con (Sắt, Dây, Đinh, Tán rút, Nút nhựa, Vật tư thành phẩm).',
        { text: 'Bấm "Duyệt" hoặc "Từ chối" — đây là MỘT quyết định duy nhất cho toàn bộ nhánh mảnh (không duyệt riêng từng nhóm vật tư).', critical: true },
        'Sau khi Duyệt, bấm "Xác nhận hoàn tất — Định mức mảnh" để chính thức chốt nhánh này.',
        'Làm tương tự cho tab "Định mức chi tiết" (Sơn/Phụ kiện/Bao bì) — độc lập, không phải chờ nhánh mảnh xong trước.',
      ],
      result:
        'Khi cả hai nhánh đã "Xác nhận hoàn tất", SKU tự động chuyển sang "Chờ sếp duyệt" — không cần thêm thao tác nào khác. Không còn bước QLSX duyệt cục bộ ở giữa.',
      warnings: [
        'Nút "Duyệt" có hộp xác nhận ghi "Không thể sửa lại quyết định này sau khi xác nhận" — nhưng trên thực tế nếu chuyên viên nhập lại dữ liệu sau đó, quyết định duyệt sẽ tự bị xoá và bạn phải duyệt lại.',
        'Nút Duyệt/Từ chối bị khoá nếu nhánh chưa có dữ liệu gì.',
      ],
      commonErrors: [
        { issue: '"Chưa duyệt đủ nhóm mảnh: còn thiếu SAT" (chữ viết tắt sau "thiếu" là tên nhóm vật tư còn trống — SAT = Sắt, tương tự cho Dây/Đinh/Sơn...)', cause: 'Bấm "Xác nhận hoàn tất" khi còn nhóm vật tư trong nhánh chưa có dữ liệu.', fix: 'Đảm bảo mọi nhóm vật tư của nhánh đã được chuyên viên nhập trước khi xác nhận hoàn tất.' },
        { issue: '"Plan form ... đã được xử lý bởi 1 request khác trong lúc chờ duyệt - không ghi đè"', cause: '2 người/2 tab cùng thao tác duyệt một lúc.', fix: 'Tải lại trang, kiểm tra trạng thái mới nhất rồi thao tác lại.' },
      ],
      statuses: [
        { name: 'Đang làm định mức', meaning: 'SKU vừa tạo hoặc vừa bị Giám đốc từ chối.' },
        { name: 'Chờ sếp duyệt', meaning: 'Cả hai nhánh đã được KHSX xác nhận hoàn tất.' },
        { name: 'Đã duyệt', meaning: 'Giám đốc đã duyệt — định mức chính thức có hiệu lực.' },
      ],
      tags: ['duyệt sku', 'định mức mảnh', 'định mức chi tiết', 'bom'],
      sourceRefs: ['src/modules/pages/ProductionPlan/SKUDetail.tsx'],
    },
    {
      id: 'pp-duyet-sku-boss',
      title: 'Duyệt cuối định mức SKU (Giám đốc)',
      roles: ['boss'],
      purpose: 'Là cổng duyệt cuối cùng cho một công thức sản phẩm trước khi đưa vào sử dụng.',
      preconditions: ['KHSX đã "Xác nhận hoàn tất" cả hai nhánh Mảnh và Chi tiết.'],
      mock: { title: 'Duyệt SKU (Giám đốc)', buttons: ['Từ chối', 'Duyệt'] },
      steps: [
        'Vào mục "Chờ sếp duyệt", mở một SKU — xem gộp cả hai nhánh trên cùng một màn.',
        { text: 'Bấm "Duyệt" để chính thức kích hoạt định mức cho sản phẩm này (bản định mức cũ, nếu có, tự động bị thay thế).', critical: true },
        { text: 'Hoặc bấm "Từ chối" — SKU quay lại cho KHSX duyệt lại từ đầu cả hai nhánh, dữ liệu định mức đã nhập vẫn được giữ nguyên.', critical: true },
      ],
      result: 'Duyệt: định mức có hiệu lực ngay, sản phẩm dùng được cho đơn hàng/lệnh sản xuất. Từ chối: SKU quay về "Đang làm định mức".',
      warnings: ['Không có tuỳ chọn duyệt riêng từng nhánh ở bước này — chỉ duyệt hoặc từ chối toàn bộ hồ sơ.'],
      tags: ['duyệt sku giám đốc', 'boss approve sku'],
      sourceRefs: ['src/modules/pages/ProductionPlan/SKUDetail.tsx'],
    },
    {
      id: 'pp-gom-dot-cat',
      title: 'Tối ưu cắt sắt (gộp đợt cắt)',
      roles: ['khsx'],
      purpose: 'Gộp nhiều SKU dùng chung loại sắt thành một đợt cắt để giảm số cây sắt phải mua và giảm sắt vụn thừa — bước tuỳ chọn trước khi lập lệnh sản xuất.',
      preconditions: ['SKU chưa được Giám đốc duyệt lệnh sản xuất (chưa qua bước này thì mới gộp/cắt riêng được).'],
      screenshot: '/guide-screens/pp-gom-dot-cat.png',
      mock: {
        title: 'Tối ưu cắt sắt',
        columns: ['SKU', 'Đơn hàng', 'Loại sắt', 'Hao hụt nếu cắt riêng'],
        rows: [['GHE-001', 'PO-2026-014', 'Ø14 x 6000mm', '8%'], ['GHE-002', 'PO-2026-015', 'Ø14 x 6000mm', '11%']],
        buttons: ['Tạo lệnh sản xuất riêng cho SKU này', 'Xác nhận gộp 2 SKU'],
      },
      steps: [
        'Xem bảng SKU, mỗi dòng hiện loại sắt và % hao hụt ước tính nếu cắt riêng (chip đỏ = vượt ngưỡng, dấu "?" = số liệu chưa đáng tin vì mẫu quá nhỏ).',
        'Tick chọn ≥2 SKU muốn gộp — khối "Nếu gộp N SKU đã chọn" tự tính lại, cho biết bớt được bao nhiêu cây sắt.',
        { text: 'Bấm "Xác nhận gộp N SKU" để tạo một lệnh gộp (Phiếu sản xuất mới).', critical: true },
        { text: 'Hoặc chỉ chọn đúng 1 SKU rồi bấm "Tạo lệnh sản xuất riêng cho SKU này" nếu không muốn gộp.', critical: false },
        'Tuỳ chọn nâng cao: mở panel "Chiều dài cây sắt" để đổi độ dài cây mặc định theo từng loại sắt; hoặc panel "Chế độ cắt" để xin duyệt mức hao hụt cao hơn bình thường (đơn gấp) — bắt buộc nhập lý do.',
      ],
      result: 'Một Phiếu sản xuất (PI) mới được tạo ở trạng thái "Đang lên kế hoạch", chuyển sang màn "Lệnh sản xuất mới" để đặt thời hạn và gửi duyệt.',
      warnings: [
        'Mọi số liệu hao hụt/số cây tiết kiệm được đều là CẬN DƯỚI ("≥"), không phải con số cam kết chính xác.',
        'SKU đã được Giám đốc duyệt thì không gộp được nữa; SKU đang thuộc một đợt gộp khác cũng không gộp tiếp được cho tới khi đợt cũ bị từ chối.',
        'Nếu chọn "Chấp nhận hao hụt cao hơn", bắt buộc nhập lý do và % hợp lệ (0–100%) thì nút xác nhận mới bật.',
      ],
      commonErrors: [
        { issue: '"Cần ít nhất 2 SKU khác nhau để gộp thành một đợt cắt"', cause: 'Chỉ tick 1 SKU mà bấm "Xác nhận gộp".', fix: 'Chọn thêm SKU, hoặc dùng nút "Tạo lệnh sản xuất riêng" nếu chỉ có 1 SKU.' },
        { issue: '"SKU đã được Sếp duyệt thì không gộp được nữa"', cause: 'SKU chọn đã qua bước duyệt lệnh sản xuất trước đó.', fix: 'Không thao tác được nữa với SKU này ở màn này.' },
        { issue: '"SKU ... đã được gom vào phiếu sản xuất rồi - không tạo mới đè lên"', cause: 'Bấm "Tạo lệnh sản xuất riêng" hai lần cho cùng một SKU.', fix: 'Kiểm tra lại danh sách Lệnh sản xuất mới, SKU này đã có PI rồi.' },
      ],
      statuses: [
        { name: 'ĐỀ XUẤT (badge)', meaning: 'Hệ thống tự gợi ý nhóm SKU nên gộp chung — vẫn cần KHSX xác nhận, không tự động gộp.' },
      ],
      tags: ['gộp đợt cắt', 'tối ưu cắt sắt', 'cutting proposal', 'gom dot cat'],
      sourceRefs: ['src/modules/pages/ProductionPlan/GomDotCatPage.tsx'],
    },
    {
      id: 'pp-lenh-sx-khsx',
      title: 'Lập lệnh sản xuất & đặt thời hạn (KHSX)',
      roles: ['khsx'],
      purpose: 'Đặt hạn cho từng công đoạn của một Phiếu sản xuất (PI), sau đó gửi cho QLSX xử lý tiếp.',
      preconditions: ['Đã có Phiếu sản xuất (PI) — tạo ra từ bước "Tối ưu cắt sắt".'],
      screenshot: '/guide-screens/pp-lenh-sx-khsx.png',
      mock: {
        title: 'Sửa thời hạn',
        formFields: ['Giao hàng', 'Mua hàng', 'Đan', 'Đóng gói', 'Khung cơ khí'],
        buttons: ['Phôi/Hàn/Sơn', 'Gửi QLSX'],
      },
      steps: [
        'Mở một PI trong danh sách "Lệnh sản xuất mới" (SKU được nhóm theo đơn hàng gốc).',
        'Bấm "Sửa thời hạn" để đặt hạn: Giao hàng, Mua hàng, Đan, Đóng gói, Khung cơ khí; bấm thêm nút "Phôi/Hàn/Sơn" để mở 3 ô hạn con nếu cần.',
        { text: 'Bấm "Gửi QLSX" — xem lại danh sách SKU rồi xác nhận "Gửi QLSX (N SKU)".', critical: true },
      ],
      result: 'PI chuyển sang chờ QLSX xử lý (chọn kho thành phẩm rồi gửi Giám đốc duyệt).',
      warnings: [
        'Ô hạn nào chưa từng được đặt tay sẽ hiển thị nhạt kèm "(ước tính)"/"(từ PO)" — nếu bấm Lưu mà không sửa, hệ thống KHÔNG ghi đè giá trị ước tính này thành ngày chính thức.',
        'Từ 2026-08-24, không gửi lẻ từng SKU được nữa — luôn gửi cả PI một lần (hệ thống tự lọc SKU đủ điều kiện, ví dụ SKU vừa bị QLSX từ chối cần gửi lại).',
      ],
      commonErrors: [
        { issue: '"... không còn SKU nào ở trạng thái gửi được (chưa gửi / bị QLSX trả lại)"', cause: 'Mọi SKU trong PI đã được gửi và đang chờ xử lý ở bước sau, không còn gì để gửi thêm.', fix: 'Kiểm tra lại trạng thái PI — có thể đã gửi thành công trước đó rồi.' },
      ],
      tags: ['lệnh sản xuất', 'thời hạn', 'production invoice', 'pi', 'gửi qlsx'],
      sourceRefs: ['src/modules/pages/ProductionPlan/LenhSXPage.tsx'],
    },
    {
      id: 'pp-lenh-sx-qlsx',
      title: 'Chọn kho thành phẩm & gửi duyệt (QLSX)',
      roles: ['qlsx'],
      purpose: 'Chọn kho thành phẩm sẽ nhận sản phẩm khi hoàn tất, trước khi trình Giám đốc duyệt cuối.',
      preconditions: ['KHSX đã gửi PI sang cho QLSX.'],
      mock: {
        title: 'Chọn kho sản xuất',
        columns: ['SKU', 'Kho thành phẩm'],
        rows: [['GHE-001', 'Kho thành phẩm 1'], ['GHE-002', 'Kho thành phẩm 2']],
        buttons: ['Áp dụng nhanh cho tất cả SKU', 'Từ chối (2 SKU)', 'Gửi sếp duyệt (2 SKU)'],
      },
      steps: [
        'Mở PI đang chờ QLSX xử lý.',
        'Bấm "Chọn kho sản xuất (N SKU)" — mở modal chọn kho thành phẩm cho từng SKU (có ô "Áp dụng nhanh cho tất cả SKU" để chọn 1 kho chung, hoặc chọn riêng từng SKU).',
        { text: 'Bấm "Gửi sếp duyệt (N SKU)" khi mọi SKU đã chọn kho.', critical: true },
        { text: 'Hoặc bấm "Từ chối (N SKU)" để trả PI về KHSX kèm lý do — thao tác này sẽ xoá PI và trả SKU về đơn hàng gốc.', critical: true },
      ],
      result: 'PI chuyển sang chờ Giám đốc duyệt cuối.',
      warnings: [
        'Từ 08/09/2026, mỗi SKU trong cùng một PI có thể chọn một kho thành phẩm khác nhau — không bắt buộc cả PI phải về chung một kho như trước.',
        'Nút "Gửi sếp duyệt" chỉ bật khi TẤT CẢ SKU đã chọn kho.',
        'Từ chối ở bước này sẽ XOÁ PI, không có đường "sửa rồi gửi lại từ chính PI cũ" — SKU quay về danh sách "Tối ưu cắt sắt" để KHSX xử lý lại từ đầu.',
      ],
      tags: ['chọn kho thành phẩm', 'qlsx duyệt', 'gửi sếp'],
      sourceRefs: ['src/modules/pages/ProductionPlan/LenhSXPage.tsx'],
    },
    {
      id: 'pp-lenh-sx-boss',
      title: 'Duyệt lệnh sản xuất (Giám đốc)',
      roles: ['boss'],
      purpose: 'Cổng duyệt quan trọng nhất trong toàn hệ thống — bấm Duyệt là xưởng bắt đầu sản xuất ngay lập tức.',
      preconditions: ['QLSX đã chọn kho thành phẩm và gửi PI lên chờ duyệt.'],
      mock: {
        title: 'Duyệt lệnh sản xuất',
        columns: ['SKU', 'Sản phẩm', 'Số lượng', 'Hạn giao'],
        rows: [['GHE-001', 'Ghế ăn mây nhựa', '200', '30/09/2026']],
        buttons: ['Từ chối cả đợt', 'Duyệt cả đợt (2 SKU)'],
      },
      steps: [
        'Mở PI đang chờ duyệt — nếu KHSX từng xin cắt đặc cách (hao hụt cao hơn bình thường), sẽ có callout riêng nêu rõ % xin và lý do.',
        { text: 'Bấm "Duyệt cả đợt (N SKU)" / "Duyệt" — xác nhận trong hộp thoại cảnh báo hành động này KHÔNG THỂ HOÀN TÁC.', critical: true },
        { text: 'Hoặc bấm "Từ chối cả đợt" / "Từ chối" — bắt buộc nhập lý do; toàn bộ PI sẽ bị xoá, SKU trả về đơn hàng gốc.', critical: true },
      ],
      result:
        'Duyệt: hệ thống tạo lệnh sản xuất chính thức tại xưởng và tự động kích hoạt tính phương án cắt sắt ngay lập tức (badge "Đang tính phương án cắt..." hiện tới khi xong, khoảng 5-15 phút).',
      warnings: [
        'Đây là hành động không thể hoàn tác — một khi đã Duyệt, xưởng bắt đầu chạy ngay.',
        'Nếu PI là đợt gộp nhiều SKU, phải Duyệt hoặc Từ chối CẢ CỤM cùng lúc — không duyệt lẻ được từng SKU trong đợt gộp.',
      ],
      commonErrors: [
        { issue: '"... là đợt gộp - phải duyệt CẢ CỤM một lần"', cause: 'Cố duyệt/từ chối lẻ một SKU trong khi PI này là đợt gộp nhiều SKU.', fix: 'Duyệt hoặc từ chối toàn bộ đợt gộp cùng lúc.' },
        { issue: '"Item ... đã được xử lý bởi 1 request khác ... - không ghi đè"', cause: '2 người cùng thao tác duyệt một PI gần như đồng thời.', fix: 'Tải lại trang để xem trạng thái mới nhất.' },
      ],
      statuses: [
        { name: 'Chờ QLSX xử lý', meaning: 'Đang chờ QLSX chọn kho và xử lý.' },
        { name: 'Chờ Giám đốc duyệt', meaning: 'Đang chờ Giám đốc duyệt cuối.' },
        { name: 'Đã duyệt', meaning: 'Lệnh sản xuất chính thức mở tại xưởng.' },
        { name: 'Bị từ chối', meaning: 'PI đã bị xoá, SKU trả về đơn hàng gốc.' },
      ],
      tags: ['duyệt lệnh sản xuất', 'boss approve', 'production order'],
      sourceRefs: ['src/modules/pages/ProductionPlan/LenhSXPage.tsx'],
    },
    {
      id: 'pp-tong-hop-vat-tu',
      title: 'Tổng hợp vật tư (tra cứu tồn kho)',
      roles: ['khsx', 'qlsx', 'boss'],
      purpose: 'Tra cứu nhanh tồn kho thật của mọi vật tư trên toàn hệ thống, không phải chỉ suy từ hoạt động sản xuất.',
      screenshot: '/guide-screens/pp-tong-hop-vat-tu.png',
      mock: {
        title: 'Tổng hợp vật tư',
        columns: ['Mã vật tư', 'Tên vật tư', 'Nhóm', 'Kho', 'Tồn kho', 'Khả dụng'],
        rows: [['SAT-004', 'Sắt hộp 20x20', 'Sắt', 'Phôi Sơn Hàn', '480', '350'], ['SON-011', 'Sơn xám RAL7035', 'Sơn', 'Vật tư TP', '5', '0']],
      },
      steps: [
        'Chọn tab nhóm vật tư (theo danh mục Admin đã khai báo) hoặc gõ tìm theo tên/mã/quy cách.',
        'Xem bảng: Mã vật tư, Tên, Quy cách, Nhóm, Kho, Tồn kho, Khả dụng (số đỏ nếu ≤0).',
        'Click một dòng để xem chi tiết: ĐVT, ĐVT mua, kho, tồn kho, khả dụng, ngày tạo.',
      ],
      result: 'Biết chính xác vật tư nào còn/hết ở kho nào, phục vụ việc lập kế hoạch và đối chiếu khi cần mua thêm.',
      warnings: [
        'Đây là màn CHỈ XEM — Kế hoạch SX không sửa được số liệu trực tiếp ở đây.',
        'Với vật tư sắt có thể tồn ở nhiều "bó" chiều dài cây khác nhau — con số Tồn kho đã được cộng dồn đúng, không chỉ lấy một dòng.',
      ],
      tags: ['tổng hợp vật tư', 'tồn kho', 'vattu dashboard'],
      sourceRefs: ['src/modules/pages/ProductionPlan/VatTuDashboardPage.tsx'],
    },
  ],
};
