import type { GuideGroup } from '../types';

// Nguồn: InboundWarehouseApp.tsx và toàn bộ trang con (NhapKhoPage, InternalTransferSections,
// WarehouseXuatPage, ChuyenKhoTuDoPage, PhanPhoiNoiBoPage + 4 sub-tab, KhoXuatDanPage,
// KhoNhapDanPage, KhoChuyenKiemPage, KhoDongGoiPage, OfficeSuppliesPage) + BE tương ứng —
// đọc trực tiếp mã nguồn 22/09/2026.
// Mỗi thủ kho chỉ thấy đúng 1 kho (warehouseScope) và đúng bộ tab của "gia đình" kho đó:
// phoi-son-han (khung cơ khí) → vat-tu-tp (vật tư thành phẩm) → thanh-pham (thành phẩm).

export const warehouseGroup: GuideGroup = {
  id: 'warehouse',
  title: 'Kho',
  icon: 'Warehouse',
  color: 'var(--fg-4338ca)',
  bg: 'var(--bg-e0e7ff)',
  roles: ['warehouse'],
  description: 'Nhập/xuất vật tư, chuyển kho nội bộ, xuất-nhập đan, chuyền kiểm, đóng gói — theo đúng kho bạn phụ trách.',
  articles: [
    {
      id: 'wh-overview',
      title: 'Kho của bạn thấy những tab nào',
      roles: ['warehouse'],
      purpose:
        'Hệ thống có 3 "gia đình" kho vật lý nối tiếp nhau: Phôi Sơn Hàn (khung cơ khí) → Vật tư thành phẩm → Thành phẩm. Mỗi tài khoản Thủ kho chỉ được gán phụ trách đúng 1 kho, và chỉ thấy bộ tab tương ứng với gia đình của kho đó.',
      steps: [
        'Kho Phôi Sơn Hàn: Vật tư, Nhập kho, Xuất theo đơn hàng, Lịch sử kho, Phân phối nội bộ, Văn phòng phẩm. (Không có "Chuyển kho ngoài đơn hàng".)',
        'Kho Vật tư thành phẩm: Vật tư, Nhập kho, Xuất theo đơn hàng, Chuyển kho ngoài đơn hàng, Lịch sử kho, Theo dõi xuất đan, Điểm đan, Văn phòng phẩm.',
        'Kho Thành phẩm: Vật tư, Nhập kho, Xuất theo đơn hàng, Chuyển kho ngoài đơn hàng, Lịch sử kho, Chuyền kiểm, Đóng gói, Theo dõi nhập đan, Văn phòng phẩm.',
      ],
      result: 'Biết chính xác mình cần thao tác ở tab nào, tránh tìm nhầm sang tab của kho khác.',
      warnings: [
        'Có thể có nhiều kho cùng một "gia đình" (ví dụ 2 kho Thành phẩm khác nhau) — mỗi kho là một kho vật lý độc lập, tồn kho KHÔNG gộp chung dù cùng gia đình.',
        'Tab "Xuất kho" đã đổi tên thành "Xuất theo đơn hàng" để phân biệt với "Chuyển kho ngoài đơn hàng" — xuất theo đơn hàng luôn gắn với một PO/PI cụ thể.',
      ],
      tags: ['tổng quan kho', 'gia đình kho', 'warehouse scope'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/InboundWarehouseApp.tsx'],
    },
    {
      id: 'wh-nhap-kho',
      title: 'Nhập kho — nhận hàng mua về',
      roles: ['warehouse'],
      purpose: 'Ghi nhận số lượng thực tế nhận được khi hàng mua về, theo đúng đề xuất mua đã được Giám đốc ký duyệt.',
      preconditions: ['Đề xuất mua đã ở trạng thái "Đang mua hàng" (Mua hàng đã bấm "Sếp đã duyệt").'],
      mock: {
        title: 'Nhập kho',
        columns: ['Vật tư', 'Cần mua', 'Đã nhận', 'Nhập thêm'],
        rows: [['Sắt hộp 20x20', '480', '300', '___']],
        buttons: ['Xác nhận'],
      },
      screenshot: '/guide-screens/wh-nhap-kho.png',
      steps: [
        'Mở tab "Nhập kho", chọn dòng vật tư cần nhận (chỉ hiện vật tư thuộc đúng kho mình phụ trách).',
        'Nhập số lượng nhận thực tế (hệ thống tự quy đổi theo đơn vị mua nếu khác đơn vị kho).',
        { text: 'Bấm "Xác nhận". Nếu số nhận vượt số đã đặt mua, hệ thống hỏi lại xác nhận nhưng vẫn cho ghi nhận.', critical: false },
      ],
      result: 'Tồn kho tăng lên đúng số đã nhận; nếu nhận đủ, đề xuất chuyển sang "Đã mua" bên Mua hàng.',
      warnings: [
        'Nếu số nhập lệch quá 5% so với gợi ý quy đổi, hệ thống cảnh báo nhưng KHÔNG chặn — vẫn ghi nhận theo số bạn nhập.',
        'Có thể nhận thành nhiều đợt (nhận thiếu vẫn ghi nhận được, nhận sau bù tiếp).',
      ],
      tags: ['nhập kho', 'nhận hàng mua', 'receive'],
      sourceRefs: ['src/modules/pages/Manufacturing/NhapKhoPage.tsx'],
    },
    {
      id: 'wh-nhap-noi-bo',
      title: 'Nhập kho — Nhập nội bộ (xác nhận phiếu chuyển đến)',
      roles: ['warehouse'],
      purpose: 'Xác nhận hoặc từ chối phiếu chuyển kho nội bộ mà kho khác gửi tới kho của bạn.',
      preconditions: ['Có phiếu chuyển kho đang ở trạng thái chờ xác nhận gửi tới kho của bạn.'],
      mock: {
        title: 'Nhập nội bộ',
        columns: ['Phiếu', 'Từ kho', 'Vật tư', 'Số lượng'],
        rows: [['CK-0142', 'Phôi Sơn Hàn', 'Mảnh tựa đã sơn', '50']],
        buttons: ['Từ chối', 'Xác nhận nhận hàng'],
      },
      screenshot: '/guide-screens/wh-nhap-noi-bo.png',
      steps: [
        { text: 'Bấm "Xác nhận nhận hàng" trên dòng phiếu → xác nhận trong hộp thoại "Tồn kho của cả 2 kho sẽ được cập nhật ngay".', critical: true },
        { text: 'Hoặc bấm "Từ chối" → bắt buộc nhập lý do → "Tồn kho của cả 2 kho sẽ KHÔNG thay đổi".', critical: false },
      ],
      result: 'Xác nhận: tồn kho của kho gửi giảm, tồn kho của bạn tăng ngay lập tức. Từ chối: không có gì thay đổi, phiếu đóng lại.',
      warnings: ['Trước khi bạn xác nhận, phiếu chuyển đang ở trạng thái chờ không ảnh hưởng tồn kho — hàng "trên đường đi" chưa được tính vào tồn kho của bên nào theo đúng nghĩa đã trừ/cộng sổ sách.'],
      commonErrors: [
        { issue: '"Phiếu chuyển kho ... đang ở trạng thái ... - chỉ phiếu đang chờ mới xác nhận được"', cause: 'Phiếu đã được xử lý (xác nhận/từ chối) trước đó rồi.', fix: 'Tải lại trang để xem trạng thái mới nhất.' },
        { issue: '"Phiếu chuyển kho ... đã được xử lý bởi 1 request khác trong lúc xác nhận - không ghi đè"', cause: 'Thao tác trùng gần như đồng thời (2 tab, 2 người cùng xử lý 1 phiếu).', fix: 'Tải lại trang rồi thao tác lại.' },
      ],
      statuses: [
        { name: 'Đang chờ xác nhận', meaning: 'Chờ kho đích xác nhận, chưa ảnh hưởng tồn kho.' },
        { name: 'Đã xác nhận', meaning: 'Tồn kho cả 2 bên đã cập nhật.' },
        { name: 'Bị từ chối', meaning: 'Không có gì thay đổi.' },
      ],
      tags: ['nhập nội bộ', 'xác nhận chuyển kho', 'phiếu chuyển kho'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/InternalTransferSections.tsx'],
    },
    {
      id: 'wh-xuat-theo-don-piece',
      title: 'Xuất theo đơn hàng — chuyển mảnh sang Vật tư thành phẩm (kho Phôi Sơn Hàn)',
      roles: ['warehouse'],
      purpose: 'Chuyển mảnh đã cắt/hàn/sơn và đã qua KCS sang kho Vật tư thành phẩm.',
      preconditions: ['Mảnh đã có kết quả KCS đạt ("Đã qua KCS").'],
      mock: {
        title: 'Xuất theo đơn hàng — chuyển mảnh',
        columns: ['Mảnh', 'Đã qua KCS', 'Có thể chuyển', 'Đã chuyển'],
        rows: [['Mảnh tựa', '200', '150', '50']],
        buttons: ['Xác nhận'],
      },
      screenshot: '/guide-screens/wh-xuat-theo-don-piece.png',
      steps: [
        'Chọn đơn hàng/mảnh cần chuyển — xem cột "Đã qua KCS", "Có thể chuyển" (đã trừ phần đang nằm trong phiếu chờ khác), "Đã chuyển".',
        'Nếu có ≥2 kho Vật tư thành phẩm, chọn kho đích ở dropdown.',
        { text: 'Bấm "Xác nhận" để tạo phiếu chuyển kho nội bộ.', critical: false },
      ],
      result: 'Tạo một phiếu chuyển kho ở trạng thái chờ xác nhận — tồn kho CHƯA đổi ngay, chỉ đổi khi kho Vật tư thành phẩm xác nhận nhận (xem bài "Nhập kho — Nhập nội bộ").',
      warnings: ['Chỉ được chuyển đúng 1 bước theo đúng chuỗi Phôi Sơn Hàn → Vật tư thành phẩm → Thành phẩm — không được nhảy cóc.'],
      commonErrors: [
        { issue: '"Không có mảnh nào đủ số lượng đã qua KCS ... để tạo phiếu chuyển kho"', cause: 'Số mảnh đã qua KCS không đủ, hoặc toàn bộ đã nằm trong một phiếu chuyển khác đang chờ xác nhận.', fix: 'Kiểm tra lại số liệu KCS và các phiếu chuyển đang chờ trước khi tạo phiếu mới.' },
      ],
      tags: ['xuất theo đơn hàng', 'chuyển mảnh', 'piece transfer'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/WarehouseXuatPage.tsx'],
    },
    {
      id: 'wh-xuat-theo-don-packaging',
      title: 'Xuất theo đơn hàng — Xuất vật tư đóng gói',
      roles: ['warehouse'],
      purpose: 'Xuất vật tư dùng để đóng gói (tem, màng bọc, thùng...) cho một đơn — đây là bước duy nhất thực sự ghi nhận hàng "về" kho thành phẩm trên sổ sách.',
      preconditions: [
        'PI (lệnh sản xuất) đang có ít nhất 1 SKU đã được QLSX bấm "Bắt đầu".',
        'Số sản phẩm tương ứng đã qua đủ Chuyền kiểm.',
      ],
      mock: {
        title: 'Xuất theo đơn hàng — Xuất vật tư đóng gói',
        columns: ['Vật tư đóng gói', 'Định mức', 'Đã xuất', 'Còn được xuất'],
        rows: [['Thùng carton 60x40', '200', '120', '80']],
        buttons: ['Xác nhận'],
      },
      screenshot: '/guide-screens/wh-xuat-theo-don-packaging.png',
      steps: [
        'Chọn đơn hàng cần xuất vật tư đóng gói — chỉ thấy vật tư mà kho của bạn đang giữ.',
        { text: 'Nhập số lượng xuất, bấm "Xác nhận".', critical: true },
      ],
      result: 'Ghi nhận NGAY vào sổ sách kho — thời điểm này hàng mới chính thức tính là "đã về" đúng kho thành phẩm đã chọn từ lúc QLSX duyệt lệnh sản xuất.',
      warnings: [
        'Đây là bước GHI TỒN KHO NGAY LẬP TỨC (khác các bước Xuất/Nhập đan hay Chuyền kiểm chỉ là ghi chép) — hãy chắc chắn số liệu đúng trước khi xác nhận.',
        'Có rủi ro xác suất thấp: 2 lệnh sản xuất xin xuất gần hết một vật tư đóng gói gần như đồng thời có thể khiến tồn kho bị âm — chưa khắc phục triệt để, cẩn trọng khi tồn kho vật tư đóng gói sắp cạn.',
      ],
      commonErrors: [
        { issue: '"Chỉ X/Y sản phẩm đã qua Chuyền kiểm ... - không thể xuất đóng gói cho ... vượt quá số đã chuyền kiểm"', cause: 'Số lượng xin xuất vượt số sản phẩm đã hoàn tất Chuyền kiểm.', fix: 'Hoàn tất Chuyền kiểm cho đủ số lượng trước khi xuất, hoặc giảm số lượng xuất.' },
        { issue: '"Số lượng xuất ... vượt quá số lượng còn có thể xuất cho vật tư ... (định mức ..., đã xuất ..., còn ...)"', cause: 'Xuất vượt định mức công thức sản xuất cho phép.', fix: 'Kiểm tra lại định mức và số đã xuất trước đó.' },
        { issue: '"Tồn kho khả dụng (...) không đủ xuất ... - kiểm tra lại tồn kho thực tế trước khi xuất"', cause: 'Kho không còn đủ vật tư đóng gói này.', fix: 'Kiểm tra tồn kho thực tế, báo Mua hàng nếu cần bổ sung.' },
        { issue: 'Không xuất được, không thấy lệnh trong danh sách', cause: 'PI chưa có SKU nào được QLSX bấm "Bắt đầu", hoặc đã "Kết thúc".', fix: 'Liên hệ QLSX kiểm tra trạng thái lệnh sản xuất.' },
      ],
      tags: ['xuất vật tư đóng gói', 'packaging issue', 'về kho thành phẩm'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/WarehouseXuatPage.tsx', 'DNA-ERP-BE/src/modules/packaging-issues/packaging-issues.service.ts'],
    },
    {
      id: 'wh-xuat-theo-don-ship',
      title: 'Xuất theo đơn hàng — Giao thành phẩm cho khách',
      roles: ['warehouse'],
      purpose: 'Ghi nhận đã giao bao nhiêu thành phẩm cho khách hàng theo đúng đơn hàng bán.',
      mock: {
        title: 'Xuất theo đơn hàng — Giao cho khách',
        columns: ['Sản phẩm', 'Kế hoạch', 'Thực có', 'Đã xuất'],
        rows: [['Ghế ăn mây nhựa', '200', '80', '120']],
        buttons: ['Xác nhận'],
      },
      screenshot: '/guide-screens/wh-xuat-theo-don-ship.png',
      steps: [
        'Chọn đơn hàng, xem "Kế hoạch" (tổng cần), "Thực có" (còn lại chưa giao), "Đã xuất".',
        { text: 'Nhập số lượng giao, bấm "Xác nhận".', critical: false },
      ],
      result: 'Số đã giao trên đơn hàng bán được cộng dồn ngay — cập nhật để Kinh doanh theo dõi.',
      warnings: ['Bước này chỉ cộng sổ số đã giao trên đơn hàng, KHÔNG đối chiếu với tồn kho vật lý thật và không ghi vào sổ tồn kho — hoàn toàn tách biệt với các bước nội bộ khác.'],
      commonErrors: [
        { issue: '"Ship ... vượt quá số lượng còn lại (đã ship .../...)"', cause: 'Số giao vượt quá số còn lại cần giao của đơn hàng.', fix: 'Kiểm tra lại số đã giao trước đó và số còn thiếu thực tế.' },
      ],
      tags: ['giao hàng', 'xuất cho khách', 'ship'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/WarehouseXuatPage.tsx'],
    },
    {
      id: 'wh-chuyen-kho-tu-do',
      title: 'Chuyển kho ngoài đơn hàng',
      roles: ['warehouse'],
      purpose: 'Chuyển bất kỳ vật tư nào, số lượng tuỳ ý, giữa 2 kho — không cần gắn với đơn hàng/lệnh sản xuất cụ thể nào.',
      preconditions: ['Không áp dụng cho kho Phôi Sơn Hàn (tab này không có ở kho đó).'],
      mock: {
        title: 'Tạo phiếu chuyển kho',
        formFields: ['Kho nguồn', 'Kho đích', 'Vật tư', 'Số lượng', 'Ghi chú'],
        buttons: ['Tạo phiếu chuyển kho'],
      },
      screenshot: '/guide-screens/wh-chuyen-kho-tu-do.png',
      steps: [
        'Kho nguồn tự khoá theo kho của bạn.',
        'Chọn Kho đích (không chọn được kho Phôi Sơn Hàn — kho này chỉ nhận vật tư qua mua hàng/nhập kho).',
        'Chọn Vật tư (hiện kèm số lượng khả dụng), nhập Số lượng (không vượt khả dụng), Ghi chú (tuỳ chọn).',
        { text: 'Bấm "Tạo phiếu chuyển kho".', critical: false },
      ],
      result: 'Tạo phiếu chuyển kho ở trạng thái chờ xác nhận, chờ kho đích xác nhận (xem bài "Nhập kho — Nhập nội bộ") mới thật sự đổi tồn kho.',
      warnings: [
        'Nếu vật tư có tồn kho chia theo từng loại chiều dài cây (đặc thù của sắt), tab này KHÔNG hỗ trợ — phải dùng đúng luồng "Phân phối nội bộ > Xuất sắt".',
        'Nếu giữa lúc mở form và lúc bấm tạo phiếu, một phiếu khác đã giữ chỗ trước một phần số lượng, hệ thống tự động GIẢM (clamp) số lượng thực tạo — kiểm tra lại thông báo sau khi tạo để biết số thực tế đã chuyển.',
      ],
      commonErrors: [
        { issue: '"... là kho ảo ... - không dùng được cho chuyển kho tự do"', cause: 'Chọn nhầm một kho ảo (điểm ghi sổ kỹ thuật) làm kho đích.', fix: 'Chỉ chọn kho vật lý thật.' },
        { issue: '"Không được chuyển kho tự do tới ... - kho Phôi Sơn Hàn chỉ nhận vật tư qua mua hàng/nhập kho"', cause: 'Cố chọn kho Phôi Sơn Hàn làm đích.', fix: 'Không chuyển tự do vào kho này — dùng đúng luồng mua hàng/nhập kho.' },
        { issue: '"Vật tư ... đã có tồn kho phân theo cỡ cây (...mm) - chuyển kho nội bộ chưa hỗ trợ chọn cỡ cây..."', cause: 'Vật tư là sắt có tồn theo nhiều chiều dài cây khác nhau.', fix: 'Dùng tab "Phân phối nội bộ > Xuất sắt trong phôi" thay vì tab này.' },
        { issue: '"Không đủ tồn kho khả dụng để tạo phiếu chuyển kho..."', cause: 'Vật tư không còn đủ số lượng khả dụng.', fix: 'Kiểm tra lại tồn kho thực tế, giảm số lượng chuyển.' },
      ],
      tags: ['chuyển kho tự do', 'chuyển kho nội bộ', 'warehouse transfer'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/ChuyenKhoTuDoPage.tsx'],
    },
    {
      id: 'wh-phan-phoi-noi-bo-sat',
      title: 'Phân phối nội bộ — Xuất sắt trong phôi (chỉ kho Phôi Sơn Hàn)',
      roles: ['warehouse'],
      purpose: 'Cấp cây sắt cho Tổ Phôi cắt, theo đúng phương án cắt sắt đã được duyệt cho lệnh sản xuất (PI).',
      preconditions: [
        'PI có ít nhất 1 SKU đã được QLSX bấm "Bắt đầu".',
        'Đã có phương án cắt sắt được duyệt cho vật tư cần xuất.',
      ],
      mock: {
        title: 'Phân phối nội bộ — Xuất sắt trong phôi',
        columns: ['Vật tư', 'Cần', 'Đã xuất', 'Còn được xuất', 'Tồn kho'],
        rows: [['Sắt hộp 20x20', '480', '200', '280', '350']],
        formFields: ['Dài cây (mm)', 'Số cây'],
        buttons: ['Xuất'],
      },
      screenshot: '/guide-screens/wh-phan-phoi-noi-bo-sat.png',
      steps: [
        'Chọn PI cần cấp sắt, chọn dòng vật tư sắt trong bảng (Cần / Đã xuất / Còn được xuất / Tồn kho).',
        'Nhập "Dài cây (mm)" (mặc định lấy theo phương án đã duyệt) và "Số cây".',
        { text: 'Bấm "Xuất" — xác nhận "Xuất {n} cây {vật tư} (dài {…}mm) cho Phôi?".', critical: true },
      ],
      result: 'Tồn kho sắt bị trừ ngay theo đúng bucket chiều dài cây; Tổ Phôi nhận được cây sắt để bắt đầu cắt.',
      warnings: ['Cột "Cần" lấy từ phương án cắt đã duyệt (số cây thực sự cần), KHÔNG phải suy trực tiếp từ định mức (công thức sản xuất).'],
      commonErrors: [
        { issue: '"Chưa có phương án cắt sắt đã duyệt cho PI này..."', cause: 'KHSX chưa tính/chưa duyệt xong phương án cắt cho PI này.', fix: 'Báo KHSX tính và duyệt phương án cắt trước khi xuất sắt.' },
        { issue: '"Tồn kho vật lý cây dài ...mm (... cây) không đủ xuất ... cây..."', cause: 'Không đủ cây sắt đúng chiều dài đó trong kho (có thể kho chỉ còn chiều dài khác, hoặc bị điều chỉnh tay).', fix: 'Kiểm tra lại tồn kho theo đúng chiều dài, báo Admin nếu nghi ngờ số liệu sai.' },
      ],
      statuses: [
        { name: 'Đã xuất', meaning: 'Chờ Phôi xác nhận nhận.' },
        { name: 'Đã nhận → Chờ KCS duyệt → KCS đã duyệt', meaning: 'Các bước tiếp theo do Tổ Phôi và KCS thực hiện.' },
      ],
      tags: ['xuất sắt', 'phân phối nội bộ', 'steel issue'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/XuatSatPage.tsx'],
    },
    {
      id: 'wh-phan-phoi-noi-bo-khac',
      title: 'Phân phối nội bộ — Xuất vật tư TP / Hàn / Sơn (chỉ kho Phôi Sơn Hàn)',
      roles: ['warehouse'],
      purpose: 'Cấp vật tư cho Tổ Phôi (vật tư thành phẩm như sắt la, thanh nhôm) hoặc Tổ Hàn/Sơn (vật tư tiêu hao: khí CO2, dây hàn, bột sơn...).',
      preconditions: ['SKU đã được Sếp duyệt lệnh sản xuất và (với vật tư TP) đã có định mức cắt theo tỷ lệ cho mảnh đó.'],
      mock: {
        title: 'Xuất vật tư TP / Hàn / Sơn',
        columns: ['Vật tư', 'Cần', 'Đã xuất', 'Còn phải xuất'],
        rows: [['Khí CO2', '40', '25', '15']],
        buttons: ['Xuất'],
      },
      screenshot: '/guide-screens/wh-phan-phoi-noi-bo-khac.png',
      steps: [
        'Chọn PO/SKU cần xuất, xem bảng Cần / Đã xuất / Còn phải xuất.',
        { text: 'Nhập số lượng xuất (không vượt "Còn phải xuất"), bấm "Xuất".', critical: false },
      ],
      result: 'Tồn kho vật tư giảm ngay; vật tư sẵn sàng cho tổ sản xuất tương ứng nhận và báo cáo sản lượng.',
      commonErrors: [
        { issue: '"Vật tư ... chưa được gán kho (Material.warehouseId) - báo Admin cấu hình trước khi xuất"', cause: 'Admin chưa gán vật tư này vào kho nào.', fix: 'Liên hệ Admin cấu hình kho cho vật tư.' },
        { issue: '"Số lượng xuất ... vượt quá số lượng còn có thể xuất ..."', cause: 'Vượt định mức cho phép.', fix: 'Kiểm tra lại định mức và số đã xuất.' },
        { issue: '"Tồn kho khả dụng ... không đủ xuất ..."', cause: 'Kho không còn đủ vật tư.', fix: 'Kiểm tra tồn kho thực tế, báo Mua hàng nếu cần.' },
        { issue: 'SKU không xuất hiện trong danh sách, kèm ghi chú thiếu định mức', cause: 'Chưa khai định mức vật tư thành phẩm cho mảnh này, hoặc SKU chưa được duyệt lệnh sản xuất.', fix: 'Báo KHSX bổ sung định mức hoặc hoàn tất duyệt lệnh sản xuất.' },
      ],
      tags: ['xuất vật tư thành phẩm', 'xuất vật tư hàn', 'xuất vật tư sơn', 'vật tư tiêu hao'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/XuatVatTuThanhPhamPage.tsx', 'src/modules/pages/InboundWarehouse/XuatVatTuTieuHaoPage.tsx'],
    },
    {
      id: 'wh-xuat-dan',
      title: 'Theo dõi xuất đan (chỉ kho Vật tư thành phẩm)',
      roles: ['warehouse'],
      purpose: 'Gửi mảnh cần đan (có Dây và Đinh) ra điểm gia công đan bên ngoài.',
      preconditions: ['Mảnh đã thực nhận đủ tại kho Vật tư thành phẩm (từ bước "Xuất theo đơn hàng — chuyển mảnh").'],
      mock: {
        title: 'Theo dõi xuất đan',
        columns: ['Mảnh', 'Điểm đan', 'Cần', 'Đã xuất', 'Còn phải xuất'],
        rows: [['Mảnh tay', 'Điểm đan Bình An', '558', '300', '258']],
        buttons: ['Xuất đan'],
      },
      screenshot: '/guide-screens/wh-xuat-dan.png',
      steps: [
        'Chọn mảnh cần gửi đan, xem Cần / Đã xuất / Còn phải xuất / Có thể xuất (số thực đã nhận về kho).',
        'Chọn Điểm đan (bắt buộc).',
        'Nhập Số lượng mảnh; hệ thống tự điền theo định mức số lượng Vật tư mang kèm (Dây/Đinh/Nút nhựa) — có thể sửa tay nhưng phải điền đủ mọi dòng.',
        { text: 'Bấm "Xuất đan".', critical: false },
      ],
      result: 'Ghi nhận đã gửi bao nhiêu mảnh cho điểm đan nào; vật tư mang kèm bị trừ tồn kho ngay. Bản thân mảnh KHÔNG bị trừ tồn kho (chỉ tạm "đi vắng" để gia công).',
      warnings: ['Bắt buộc điền đủ số lượng cho mọi vật tư mang kèm trước khi xuất được — không được bỏ trống dòng nào.'],
      commonErrors: [
        { issue: '"Vượt số mảnh thực tế đã nhận từ kho phôi-sơn-hàn (chỉ còn ... có thể xuất)"', cause: 'Số muốn gửi đan vượt số mảnh thực đã về kho Vật tư thành phẩm.', fix: 'Kiểm tra lại số đã nhận thực tế trước khi gửi đan.' },
        { issue: '"Điểm đan ... đã ngừng hoạt động - không thể xuất đan mới cho điểm này"', cause: 'Điểm đan đã bị vô hiệu hoá.', fix: 'Chọn điểm đan khác đang hoạt động.' },
        { issue: '"Số lượng xuất đan ... vượt quá số lượng còn có thể xuất cho mảnh ..."', cause: 'Vượt định mức đan cho phép.', fix: 'Kiểm tra lại định mức đan của mảnh.' },
      ],
      tags: ['xuất đan', 'gửi đan', 'điểm đan', 'weaving issue'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/KhoXuatDanPage.tsx'],
    },
    {
      id: 'wh-nhap-dan',
      title: 'Theo dõi nhập đan (chỉ kho Thành phẩm)',
      roles: ['warehouse'],
      purpose: 'Xác nhận đã nhận lại mảnh đã đan xong từ điểm đan gia công ngoài.',
      mock: {
        title: 'Theo dõi nhập đan',
        columns: ['Mảnh', 'Điểm đan', 'Đã xuất', 'Đã nhận', 'Còn phải nhận'],
        rows: [['Mảnh tay', 'Điểm đan Bình An', '300', '250', '50']],
        buttons: ['Nhận'],
      },
      screenshot: '/guide-screens/wh-nhap-dan.png',
      steps: [
        'Chọn dòng (mảnh, điểm đan) cần nhận — xem Đã xuất / Đã nhận / Còn phải nhận.',
        { text: 'Nhập số lượng nhận về, bấm "Nhận" — xác nhận "Tồn kho thành phẩm sẽ được cộng ngay".', critical: false },
      ],
      result: 'Có bằng chứng đối chiếu đã nhận đủ hàng từ điểm đan — làm căn cứ cho bước Chuyền kiểm tiếp theo.',
      warnings: [
        'Đây chỉ là bước ĐỐI CHIẾU số liệu với điểm đan (đã gửi bao nhiêu / đã nhận lại bao nhiêu), không phải nhập kho thành phẩm thật sự trên sổ sách — mảnh vẫn được tính thuộc kho Vật tư thành phẩm cho tới khi Xuất vật tư đóng gói.',
        'Kiểm đếm hàng đan diễn ra hoàn toàn bằng tay ngoài phần mềm; hệ thống chỉ ghi nhận số bạn nhập.',
      ],
      commonErrors: [
        { issue: '"Số lượng nhập đan ... vượt quá số lượng điểm đan ... còn giữ cho mảnh ..."', cause: 'Số nhận vượt số điểm đan đó đang thực giữ (đã xuất trừ đã nhận trước đó).', fix: 'Đối chiếu lại sổ sách xuất đan trước khi nhập.' },
      ],
      tags: ['nhập đan', 'nhận hàng đan', 'weaving receipt'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/KhoNhapDanPage.tsx'],
    },
    {
      id: 'wh-chuyen-kiem',
      title: 'Chuyền kiểm',
      roles: ['warehouse'],
      purpose: 'Kiểm tra chất lượng lần cuối cho từng mảnh trước khi được phép đóng gói — bắt buộc cho MỌI mảnh, kể cả mảnh không cần đan.',
      preconditions: ['Mảnh đã "Hiện có" > 0 (mảnh có đan: đã nhập đan về; mảnh không đan: đã có phiếu chuyển kho nội bộ được xác nhận).'],
      mock: {
        title: 'Chuyền kiểm',
        columns: ['Mảnh', 'Tổng cần', 'Hiện có', 'Đã kiểm', 'Lỗi'],
        rows: [['Mảnh tay (có đan)', '558', '200', '150', '3'], ['Chân nhôm (không đan)', '279', '0', '0', '0'], ['Pat (không đan)', '279', '279', '100', '1']],
        buttons: ['Kiểm'],
      },
      screenshot: '/guide-screens/wh-chuyen-kiem.png',
      steps: [
        'Xem bảng: Tổng cần / Hiện có / Đã kiểm / Lỗi cho từng mảnh.',
        { text: 'Bấm "Kiểm" (mờ nếu Đã kiểm ≥ Hiện có) → nhập Số lượng đã kiểm (không vượt phần còn lại có thể kiểm).', critical: false },
        'Nếu có lỗi: bấm "Thêm lỗi", nhập lý do, có thể đính kèm ảnh cho từng lỗi.',
        { text: 'Bấm "Xác nhận".', critical: false },
      ],
      result: 'Số đã kiểm cộng dồn cho mảnh này. Một sản phẩm chỉ "qua đủ Chuyền kiểm" khi TẤT CẢ các mảnh cấu thành đã đạt đủ số lượng kiểm tương ứng.',
      warnings: [
        'Số kiểm tối đa còn lại = Hiện có − Đã kiểm, và không được vượt Tổng cần − Đã kiểm — nhập vượt sẽ bị chặn cả trên giao diện lẫn khi gửi lên máy chủ.',
        'Việc chặn vượt ở máy chủ là kiểu "đọc rồi mới ghi" chứ không khoá cứng — 2 người kiểm cùng một mảnh cùng lúc có thể vượt vài đơn vị trong trường hợp hiếm.',
      ],
      commonErrors: [
        { issue: '"Vượt quá số lượng còn lại có thể kiểm"', cause: 'Nhập số kiểm vượt phần Hiện có − Đã kiểm.', fix: 'Kiểm tra lại số liệu, nhập không vượt phần còn lại.' },
        { issue: 'Nút "Kiểm" bị mờ, tooltip "Chưa có hàng về để kiểm"', cause: '"Hiện có" đang bằng 0 — chưa có phiếu nhập đan/chuyển kho nội bộ nào được xác nhận cho mảnh này.', fix: 'Kiểm tra phiếu nhập đan (mảnh có đan) hoặc phiếu chuyển kho nội bộ (mảnh không đan) đã được xác nhận chưa.' },
      ],
      tags: ['chuyền kiểm', 'kiểm tra chất lượng', 'transfer check'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/KhoChuyenKiemPage.tsx', 'docs/quy-trinh-2026-09-19-chuyen-kiem-hien-co.html'],
    },
    {
      id: 'wh-dong-goi',
      title: 'Đóng gói (đếm thùng)',
      roles: ['warehouse'],
      purpose: 'Đếm và ghi nhận số thùng thành phẩm đã đóng gói xong — KHÁC với "Xuất vật tư đóng gói" (nơi trừ tem/màng bọc và ghi tồn kho thật).',
      mock: {
        title: 'Đóng gói',
        columns: ['Sản phẩm', 'Tổng thùng', 'Đã đóng gói', 'Còn lại'],
        rows: [['Ghế ăn mây nhựa', '200', '120', '80']],
        buttons: ['Đóng gói'],
      },
      screenshot: '/guide-screens/wh-dong-goi.png',
      steps: [
        'Xem Tổng thùng / Đã đóng gói / Còn lại cho từng sản phẩm.',
        { text: 'Bấm "Đóng gói", nhập Số thùng đã đóng, bấm "Xác nhận".', critical: false },
      ],
      result: 'Số liệu tiến độ đóng thùng được cập nhật, phục vụ báo cáo — không làm thay đổi tồn kho chính thức.',
      warnings: [
        'Không bắt buộc phải chờ Chuyền kiểm xong hết mới được đếm thùng — đây là lựa chọn có chủ đích, không phải thiếu sót.',
        'Đừng nhầm màn này với nút "Xác nhận" ở "Xuất theo đơn hàng > Xuất vật tư đóng gói" — đó mới là bước thật sự ghi hàng "về" kho thành phẩm trên sổ sách.',
      ],
      commonErrors: [
        { issue: '"Vượt quá số lượng còn lại cần đóng gói"', cause: 'Số thùng nhập vượt phần còn lại của lệnh sản xuất.', fix: 'Kiểm tra lại số đã đóng trước đó.' },
      ],
      tags: ['đóng gói', 'đóng thùng', 'packaging record'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/KhoDongGoiPage.tsx'],
    },
    {
      id: 'wh-van-phong-pham',
      title: 'Văn phòng phẩm',
      roles: ['warehouse'],
      purpose: 'Quản lý vật tư sinh hoạt/văn phòng (bút, giấy...) của kho mình — hoàn toàn tách biệt khỏi vật tư sản xuất.',
      mock: {
        title: 'Văn phòng phẩm',
        columns: ['Tên vật tư', 'ĐVT', 'Tồn kho'],
        rows: [['Giấy A4', 'ram', '12'], ['Bút bi', 'cây', '30']],
        buttons: ['Thêm vật tư'],
      },
      screenshot: '/guide-screens/wh-van-phong-pham.png',
      steps: [
        'Bấm "Thêm vật tư": nhập Tên vật tư, Đơn vị tính (bắt buộc), Ghi chú, Tồn ban đầu.',
        'Trên mỗi dòng: bấm icon Nhập/Xuất để điều chỉnh số lượng (nhập Số lượng + Ghi chú, bấm "Xác nhận nhập/xuất").',
        'Bấm icon Lịch sử để xem lại toàn bộ lần nhập/xuất/điều chỉnh của vật tư đó.',
        { text: 'Bấm icon Sửa để đổi tên/đơn vị/ghi chú; bấm icon Xoá để xoá vật tư (vẫn giữ lịch sử để tra cứu).', critical: false },
      ],
      result: 'Tồn kho văn phòng phẩm được theo dõi riêng theo từng kho vật lý, không ảnh hưởng tới tồn kho sản xuất.',
      commonErrors: [
        { issue: '"Không đủ tồn để xuất, hoặc vật tư đã bị xoá/thay đổi - tải lại trang và thử lại"', cause: 'Xuất vượt tồn hiện có, hoặc dữ liệu vừa bị đổi bởi thao tác khác.', fix: 'Tải lại trang, kiểm tra tồn kho hiện tại rồi thử lại.' },
        { issue: '"Vật tư văn phòng ... đã tồn tại trong kho này"', cause: 'Tạo trùng mã vật tư đã có trong kho.', fix: 'Dùng lại dòng đã có thay vì tạo mới.' },
      ],
      tags: ['văn phòng phẩm', 'office supplies'],
      sourceRefs: ['src/modules/pages/InboundWarehouse/OfficeSuppliesPage.tsx'],
    },
  ],
};
